"""NARCISSUS clean-label backdoor attack.

The trigger is an additive, per-pixel L_inf-bounded perturbation generated by
optimizing it to match the internal feature representations of the target
class (using a surrogate model trained with POOD data). For our recreation
we ship the upstream pre-generated trigger (ResNet-18 / CIFAR-10 / target
class 2 / epsilon = 32/255) so we don't have to re-run the multi-hour
trigger-generation pipeline just to plot Figure 3.

The trigger is applied as:
    poisoned = clip(image + trigger, 0, 1)

Reference: Zeng et al. "Narcissus: A Practical Clean-Label Backdoor Attack
with Limited Information." ACM CCS 2023. arXiv:2204.05255.
Upstream: https://github.com/reds-lab/Narcissus
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import torch

TriggerFn = "Callable[[torch.Tensor], torch.Tensor]"

DEFAULT_TRIGGER_PATH = Path(__file__).parent / "triggers" / "narcissus_resnet18_cifar10_class2.npy"


def make_trigger_fn(trigger_path: str | Path | None = None) -> TriggerFn:
    """Return a `trigger_fn` that adds the NARCISSUS trigger and clamps to [0,1].

    Args:
        trigger_path: path to a `.npy` file with shape (1, 3, H, W) or (3, H, W),
            in additive [-eps, eps] space. Defaults to the upstream-bundled
            trigger for ResNet-18 / CIFAR-10 / target class 2.
    """
    path = Path(trigger_path) if trigger_path else DEFAULT_TRIGGER_PATH
    arr = np.load(path)
    if arr.ndim == 3:
        arr = arr[np.newaxis, ...]
    if arr.ndim != 4 or arr.shape[1] != 3:
        raise ValueError(f"unexpected trigger shape {arr.shape}; want (1,3,H,W)")
    trigger = torch.from_numpy(arr).float()

    def trigger_fn(images: torch.Tensor) -> torch.Tensor:
        if images.shape[-2:] != trigger.shape[-2:]:
            raise ValueError(
                f"trigger spatial size {tuple(trigger.shape[-2:])} "
                f"!= image size {tuple(images.shape[-2:])}"
            )
        t = trigger.to(images.device, images.dtype)
        return (images + t).clamp(0, 1)

    return trigger_fn
